/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sal.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sal.gui.core.fileUtils;

/**
 *
 * @author Salvatore Minasola
 */
public class editInventory extends javax.swing.JDialog {
    private JTable inv;
    private int selectedRow;
    JLabel label;
    
    

    /**
     * Creates new form editInventory
     */
    public editInventory(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public editInventory(java.awt.Frame parent, boolean modal,String codice,String denominazione,String prezzo,String quantita,JTable inv,int selectedRow,JLabel label) {
        super(parent, modal);
        initComponents();
        
        this.codice.setText(codice);
        this.denominazione.setText(denominazione);
        this.prezzo.setText(prezzo);
        this.quantita.setText(quantita);
        this.inv = inv;
        this.selectedRow = selectedRow;
        this.label = label;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codice = new javax.swing.JTextField();
        denominazione = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        prezzo = new javax.swing.JFormattedTextField();
        quantita = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(398, 250));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("CODICE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("DESCRIZIONE");
        jLabel2.setPreferredSize(new java.awt.Dimension(110, 31));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("PREZZO");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("QUANTITA");

        codice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        codice.setPreferredSize(new java.awt.Dimension(64, 28));
        codice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codiceActionPerformed(evt);
            }
        });
        codice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codiceKeyPressed(evt);
            }
        });

        denominazione.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        denominazione.setPreferredSize(new java.awt.Dimension(64, 28));
        denominazione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                denominazioneMousePressed(evt);
            }
        });
        denominazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denominazioneActionPerformed(evt);
            }
        });
        denominazione.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                denominazioneKeyPressed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(255, 204, 102));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_edit.setText("MODIFICA");
        btn_edit.setMaximumSize(new java.awt.Dimension(85, 23));
        btn_edit.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editMousePressed(evt);
            }
        });
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_close.setBackground(new java.awt.Color(255, 51, 51));
        btn_close.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_close.setText("ANNULLA");
        btn_close.setMaximumSize(new java.awt.Dimension(85, 23));
        btn_close.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        prezzo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        prezzo.setMargin(null);
        prezzo.setMinimumSize(new java.awt.Dimension(64, 31));
        prezzo.setPreferredSize(new java.awt.Dimension(64, 31));
        prezzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                prezzoMousePressed(evt);
            }
        });
        prezzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prezzoActionPerformed(evt);
            }
        });
        prezzo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prezzoKeyPressed(evt);
            }
        });

        quantita.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        quantita.setMargin(null);
        quantita.setMinimumSize(new java.awt.Dimension(64, 31));
        quantita.setPreferredSize(new java.awt.Dimension(64, 31));
        quantita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                quantitaMousePressed(evt);
            }
        });
        quantita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitaActionPerformed(evt);
            }
        });
        quantita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantitaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codice, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(denominazione, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantita, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(denominazione, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quantita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codiceActionPerformed
        denominazione.requestFocus();
    }//GEN-LAST:event_codiceActionPerformed

    private void codiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codiceKeyPressed

    }//GEN-LAST:event_codiceKeyPressed

    private void denominazioneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_denominazioneMousePressed
        
    }//GEN-LAST:event_denominazioneMousePressed

    private void denominazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denominazioneActionPerformed
        prezzo.requestFocus();
    }//GEN-LAST:event_denominazioneActionPerformed

    private void denominazioneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_denominazioneKeyPressed

    }//GEN-LAST:event_denominazioneKeyPressed

    private void btn_editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMousePressed
        errorMsg err = new errorMsg(null,true);
        err.setLocationRelativeTo(this);
        if(codice.getText().equals("")){
            err.setMessage("Il campo codice non puo essere vuoto.");
            err.setVisible(true);
        } else if(codice.getText().matches(".*[^a-zA-Z0-9].*")){
            err.setMessage("Il campo codice non puo contenere carratteri speciali.");
            err.setVisible(true);
        }else if(denominazione.getText().equals("")){
            err.setMessage("Il campo denominazione non puo essere vuoto.");
            err.setVisible(true);
        }else if(denominazione.getText().matches(".*\\\\s[^a-zA-Z0-9]\\\\s.*")){
            err.setMessage("Il campo denominazione non puo contenere carratteri speciali.");
            err.setVisible(true);
        } else if(prezzo.getText().equals("")){
            err.setMessage("Il campo prezzo non puo essere vuoto.");
            err.setVisible(true);
        } else if(quantita.getText().equals("")){
            err.setMessage("Il campo quantita' non puo essere vuoto.");
            err.setVisible(true);
        } else if(!prezzo.getText().matches("[0-9,.]+")){
            err.setMessage("Il campo prezzo deve contenere solo numeri");
            err.setVisible(true);
        } else if(!quantita.getText().matches("[0-9]+")){
            err.setMessage("Il campo quantita' deve contenere solo numeri");
            err.setVisible(true);
        }
        else {
            inv.setValueAt(codice.getText(), selectedRow, 0);
            inv.setValueAt(denominazione.getText(), selectedRow, 1);
            inv.setValueAt(Float.valueOf(prezzo.getText().replace(",", ".")), selectedRow, 2);
            inv.setValueAt(Integer.valueOf(quantita.getText()), selectedRow, 3);
            label.setText(String.valueOf(Home.countItemsInventory(inv.getModel())));
            try {
                fileUtils.salvaInventario((DefaultTableModel) inv.getModel(), "./inventario.txt");
            } catch (IOException ex) {
                Logger.getLogger(editInventory.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }

    }//GEN-LAST:event_btn_editMousePressed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void prezzoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prezzoMousePressed
        
    }//GEN-LAST:event_prezzoMousePressed

    private void prezzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prezzoActionPerformed
 
        quantita.requestFocus();
    }//GEN-LAST:event_prezzoActionPerformed

    private void prezzoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prezzoKeyPressed

    }//GEN-LAST:event_prezzoKeyPressed

    private void quantitaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantitaMousePressed
        
    }//GEN-LAST:event_quantitaMousePressed

    private void quantitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitaActionPerformed
        errorMsg err = new errorMsg(null,true);
        err.setLocationRelativeTo(this);
        if(codice.getText().equals("")){
            err.setMessage("Il campo codice non puo essere vuoto.");
            err.show();
        } else if(codice.getText().matches(".*[^a-zA-Z0-9].*")){
            err.setMessage("Il campo codice non puo contenere carratteri speciali.");
            err.show();
        }else if(denominazione.getText().equals("")){
            err.setMessage("Il campo denominazione non puo essere vuoto.");
            err.show();
        }else if(denominazione.getText().matches(".*[^a-zA-Z0-9].*")){
            err.setMessage("Il campo denominazione non puo contenere carratteri speciali.");
            err.show();
        } else if(prezzo.getText().equals("")){
            err.setMessage("Il campo prezzo non puo essere vuoto.");
            err.show();
        } else if(quantita.getText().equals("")){
            err.setMessage("Il campo quantita' non puo essere vuoto.");
            err.show();
        }else if(!prezzo.getText().matches("[0-9,.]+")){
            err.setMessage("Il campo prezzo deve contenere solo numeri");
            err.setVisible(true);
        } else if(!quantita.getText().matches("[0-9]+")){
            err.setMessage("Il campo quantita' deve contenere solo numeri");
            err.setVisible(true);
        }else {
            inv.setValueAt(codice.getText(), selectedRow, 0);
            inv.setValueAt(denominazione.getText(), selectedRow, 1);
            inv.setValueAt(Float.valueOf(prezzo.getText().replace(",", ".")), selectedRow, 2);
            inv.setValueAt(Integer.valueOf(quantita.getText()), selectedRow, 3);
            try {
                fileUtils.salvaInventario((DefaultTableModel) inv.getModel(), "./inventario.txt");
            } catch (IOException ex) {
                Logger.getLogger(editInventory.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_quantitaActionPerformed

    private void quantitaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantitaKeyPressed

    }//GEN-LAST:event_quantitaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                editInventory dialog = new editInventory(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_edit;
    private javax.swing.JTextField codice;
    private javax.swing.JTextField denominazione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField prezzo;
    private javax.swing.JFormattedTextField quantita;
    // End of variables declaration//GEN-END:variables
}
