package sal.gui;


import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.jfree.chart.ChartPanel;
import sal.gui.core.Prodotto;
import sal.gui.core.fileUtils;

/**
 *
 * @author Salvatore Minasola
 */
public class Home extends javax.swing.JFrame {

    public Color sColor = new Color(188,113,0);
    public Color dColor = new Color(255,153,0);
    public int active = 1;
    public TableRowSorter<TableModel> sorter;
    private ChartPanel dailyChart;
    private ChartPanel weeklyChart;
    
    /**
     * Creates new form Home
     */
    public Home() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        tab_ven.setModel(fileUtils.getVendite("./vendite.txt")); 
        tab_inv.setModel(fileUtils.getInventario("./inventario.txt"));
        sorter = new TableRowSorter<TableModel>(tab_inv.getModel());
        tab_inv.setRowSorter(sorter);
        rP1_inv.setText(String.valueOf(countItemsInventory(tab_inv.getModel())));
        rP1_inv1.setText(Util.getTotProdottiVendutiGiornata((DefaultTableModel) tab_ven.getModel()));
        rP1_inv2.setText(""+Util.getTotGiorno((DefaultTableModel) tab_ven.getModel(),LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))));
        insertDataComboBoxs();
        
        dailyChart = Util.createPanelChartDaily((DefaultTableModel) tab_ven.getModel(),jComboBox1.getSelectedItem().toString());
        dailyChart.setPreferredSize(new Dimension(643, 255));
        panelChartD.setLayout(new java.awt.CardLayout());
        panelChartD.add(dailyChart);
        
        
        weeklyChart = Util.createPanelChartWeekly((DefaultTableModel) tab_ven.getModel(),jComboBox2.getSelectedItem().toString().substring(0, 10));
        weeklyChart.setPreferredSize(new Dimension(643,255));
        panelChartW.setLayout(new java.awt.CardLayout());
        panelChartW.add(weeklyChart);
        
        sortByColumn(tab_ven);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sideLeftPanel = new javax.swing.JPanel();
        sideLeftPanel_text = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        p1_text = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        p2_text = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        p3_text = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        p4_text = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        rp1 = new javax.swing.JPanel();
        counterInvPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rP1_inv = new javax.swing.JLabel();
        counterVenPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rP1_inv1 = new javax.swing.JLabel();
        counterVenPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        rP1_inv2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        rp2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_inv = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        searchBarInventario = new javax.swing.JTextField();
        rp3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tab_ven = new javax.swing.JTable();
        btn_add1 = new javax.swing.JButton();
        btn_show = new javax.swing.JButton();
        rp4 = new javax.swing.JPanel();
        panelChartD = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        panelChartW = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Venero v1.1.5");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(900, 640));
        setResizable(false);

        sideLeftPanel.setBackground(new java.awt.Color(255, 153, 0));

        sideLeftPanel_text.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        sideLeftPanel_text.setText("Venero");

        panel1.setBackground(new java.awt.Color(188, 113, 0));
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel1MousePressed(evt);
            }
        });

        p1_text.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        p1_text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sal/images/Home.png"))); // NOI18N
        p1_text.setText("PAGINA INIZIALE");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p1_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p1_text)
                .addContainerGap())
        );

        panel2.setBackground(new java.awt.Color(255, 153, 0));
        panel2.setPreferredSize(new java.awt.Dimension(240, 44));
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel2MousePressed(evt);
            }
        });

        p2_text.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        p2_text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sal/images/inv_1.png"))); // NOI18N
        p2_text.setText("INVENTARIO");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p2_text, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(p2_text, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel3.setBackground(new java.awt.Color(255, 153, 0));
        panel3.setPreferredSize(new java.awt.Dimension(240, 44));
        panel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel3MousePressed(evt);
            }
        });

        p3_text.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        p3_text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sal/images/cash.png"))); // NOI18N
        p3_text.setText("VENDITA");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p3_text, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p3_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel4.setBackground(new java.awt.Color(255, 153, 0));
        panel4.setPreferredSize(new java.awt.Dimension(240, 44));
        panel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel4MousePressed(evt);
            }
        });

        p4_text.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        p4_text.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sal/images/chart.png"))); // NOI18N
        p4_text.setText("STATISTICHE");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p4_text, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p4_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideLeftPanelLayout = new javax.swing.GroupLayout(sideLeftPanel);
        sideLeftPanel.setLayout(sideLeftPanelLayout);
        sideLeftPanelLayout.setHorizontalGroup(
            sideLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sideLeftPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(sideLeftPanel_text)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sideLeftPanelLayout.createSequentialGroup()
                .addGroup(sideLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sideLeftPanelLayout.setVerticalGroup(
            sideLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLeftPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(sideLeftPanel_text)
                .addGap(25, 25, 25)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightPanel.setBackground(new java.awt.Color(204, 204, 204));
        rightPanel.setLayout(new java.awt.CardLayout());

        rp1.setBackground(new java.awt.Color(214, 214, 214));
        rp1.setEnabled(false);
        rp1.setPreferredSize(new java.awt.Dimension(616, 536));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("No. di prodotti in inventario  ");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        rP1_inv.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        rP1_inv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rP1_inv.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rP1_inv, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rP1_inv, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout counterInvPanelLayout = new javax.swing.GroupLayout(counterInvPanel);
        counterInvPanel.setLayout(counterInvPanelLayout);
        counterInvPanelLayout.setHorizontalGroup(
            counterInvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(counterInvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(counterInvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        counterInvPanelLayout.setVerticalGroup(
            counterInvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(counterInvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("No. di prodotti venduti oggi  ");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        rP1_inv1.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        rP1_inv1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rP1_inv1.setText("0");
        rP1_inv1.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rP1_inv1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rP1_inv1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout counterVenPanelLayout = new javax.swing.GroupLayout(counterVenPanel);
        counterVenPanel.setLayout(counterVenPanelLayout);
        counterVenPanelLayout.setHorizontalGroup(
            counterVenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(counterVenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(counterVenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        counterVenPanelLayout.setVerticalGroup(
            counterVenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(counterVenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Totale vendite giornaliere");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 102)));

        jPanel6.setBackground(new java.awt.Color(0, 204, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        rP1_inv2.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        rP1_inv2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rP1_inv2.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rP1_inv2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rP1_inv2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout counterVenPanel1Layout = new javax.swing.GroupLayout(counterVenPanel1);
        counterVenPanel1.setLayout(counterVenPanel1Layout);
        counterVenPanel1Layout.setHorizontalGroup(
            counterVenPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(counterVenPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(counterVenPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        counterVenPanel1Layout.setVerticalGroup(
            counterVenPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(counterVenPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Notizie e aggiornamenti");

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("03/01/2024");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Phasellus eget est et libero fringilla fermentum. Sed vel condimentum nulla. Proin sit amet dolor sed sapien lobortis lacinia. Morbi et ex ac leo accumsan fringilla. Duis nec odio non dolor interdum convallis. Cras ac lacus vitae ligula sollicitudin efficitur. Sed in eros urna. Sed nec leo vitae nisi cursus finibus. Integer dapibus arcu ac metus ultrices, sit amet tincidunt velit efficitur. Quisque lobortis, urna eu fermentum pellentesque, justo eros viverra turpis, nec condimentum libero mauris sed sapien. Sed nec posuere nisi. Phasellus sodales neque vel orci sodales, nec dapibus lorem lobortis. Sed nec nisi ut leo hendrerit blandit.");
        jTextArea2.setBorder(null);
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea2.setSelectionColor(new java.awt.Color(255, 153, 0));
        jScrollPane2.setViewportView(jTextArea2);

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("15/06/2023");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Phasellus eget est et libero fringilla fermentum. Sed vel condimentum nulla. Proin sit amet dolor sed sapien lobortis lacinia. Morbi et ex ac leo accumsan fringilla. Duis nec odio non dolor interdum convallis. Cras ac lacus vitae ligula sollicitudin efficitur. Sed in eros urna. Sed nec leo vitae nisi cursus finibus. Integer dapibus arcu ac metus ultrices, sit amet tincidunt velit efficitur. Quisque lobortis, urna eu fermentum pellentesque, justo eros viverra turpis, nec condimentum libero mauris sed sapien. Sed nec posuere nisi. Phasellus sodales neque vel orci sodales, nec dapibus lorem lobortis. Sed nec nisi ut leo hendrerit blandit.");
        jTextArea3.setBorder(null);
        jTextArea3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea3.setSelectionColor(new java.awt.Color(255, 153, 0));
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rp1Layout = new javax.swing.GroupLayout(rp1);
        rp1.setLayout(rp1Layout);
        rp1Layout.setHorizontalGroup(
            rp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rp1Layout.createSequentialGroup()
                        .addComponent(counterInvPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(counterVenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(counterVenPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        rp1Layout.setVerticalGroup(
            rp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rp1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(rp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(counterVenPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(counterVenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(counterInvPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        rightPanel.add(rp1, "card2");

        rp2.setBackground(new java.awt.Color(214, 214, 214));
        rp2.setPreferredSize(new java.awt.Dimension(616, 536));

        tab_inv.setAutoCreateRowSorter(true);
        tab_inv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Patatine", "AN12341",  new Float(2.0),  new Integer(20)},
                {"Mouse", "GH12312",  new Float(40.0),  new Integer(5)},
                {"Gioco", "AF12314",  new Float(5.0),  new Integer(50)},
                {"Barretta", "BV123141",  new Float(2.0),  new Integer(15)},
                {"Latte", "AB12345",  new Float(143.0),  new Integer(10)},
                {"Bo3", "5030917162572",  new Float(60.0),  new Integer(5)}
            },
            new String [] {
                "Nome", "Codice", "Prezzo", "Quantita"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_inv.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tab_inv.setShowGrid(true);
        tab_inv.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tab_inv);

        btn_add.setBackground(new java.awt.Color(255, 153, 0));
        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sal/images/Plus.png"))); // NOI18N
        btn_add.setText("AGGIUNGI");
        btn_add.setMaximumSize(new java.awt.Dimension(85, 23));
        btn_add.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addMousePressed(evt);
            }
        });
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(255, 153, 0));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sal/images/Edit_1.png"))); // NOI18N
        btn_edit.setText("MODIFICA");
        btn_edit.setMaximumSize(new java.awt.Dimension(85, 23));
        btn_edit.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_del.setBackground(new java.awt.Color(255, 153, 0));
        btn_del.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sal/images/Trash Can.png"))); // NOI18N
        btn_del.setText("RIMUOVI");
        btn_del.setMaximumSize(new java.awt.Dimension(85, 23));
        btn_del.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_delMousePressed(evt);
            }
        });
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sal/images/Search.png"))); // NOI18N

        searchBarInventario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchBarInventario.setText("Ricerca prodotti...");
        searchBarInventario.setBorder(null);
        searchBarInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchBarInventarioMousePressed(evt);
            }
        });
        searchBarInventario.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                searchBarInventarioInputMethodTextChanged(evt);
            }
        });
        searchBarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarInventarioActionPerformed(evt);
            }
        });
        searchBarInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchBarInventarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchBarInventarioKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(searchBarInventario))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchBarInventario)
        );

        javax.swing.GroupLayout rp2Layout = new javax.swing.GroupLayout(rp2);
        rp2.setLayout(rp2Layout);
        rp2Layout.setHorizontalGroup(
            rp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rp2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        rp2Layout.setVerticalGroup(
            rp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rp2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        rightPanel.add(rp2, "card3");

        rp3.setBackground(new java.awt.Color(214, 214, 214));

        jScrollPane4.setPreferredSize(new java.awt.Dimension(482, 402));

        tab_ven.setAutoCreateRowSorter(true);
        tab_ven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1",  new Float(200.0), null, "2024-05-23T09:34"},
                {"2",  new Float(500.0), null, "2024-05-23T17:23"},
                {"3",  new Float(431.0), null, "2024-05-25T14:55"},
                {"4",  new Float(543.0), null, "2024-05-25T19:45"},
                {"5",  new Float(321.0), null, "2024-05-27T11:34"},
                {"6",  new Float(222.0), null, "2024-05-27T16:23"},
                {"7",  new Float(500.0), null, "2024-05-29T09:12"},
                {"8",  new Float(200.0), null, "2024-05-29T18:33"}
            },
            new String [] {
                "Numero", "Totale", "Prodotti", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_ven.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tab_ven.setShowGrid(true);
        tab_ven.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tab_ven);
        if (tab_ven.getColumnModel().getColumnCount() > 0) {
            tab_ven.getColumnModel().getColumn(2).setMinWidth(0);
            tab_ven.getColumnModel().getColumn(2).setPreferredWidth(0);
            tab_ven.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        btn_add1.setBackground(new java.awt.Color(0, 153, 51));
        btn_add1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sal/images/Plus.png"))); // NOI18N
        btn_add1.setText("MODALITA VENDITA");
        btn_add1.setMaximumSize(new java.awt.Dimension(85, 23));
        btn_add1.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_add1MousePressed(evt);
            }
        });
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });

        btn_show.setBackground(new java.awt.Color(255, 204, 102));
        btn_show.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_show.setText("SCONTRINO");
        btn_show.setMaximumSize(new java.awt.Dimension(85, 23));
        btn_show.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_showMousePressed(evt);
            }
        });
        btn_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rp3Layout = new javax.swing.GroupLayout(rp3);
        rp3.setLayout(rp3Layout);
        rp3Layout.setHorizontalGroup(
            rp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rp3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btn_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_show, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        rp3Layout.setVerticalGroup(
            rp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rp3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_show, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        rightPanel.add(rp3, "card4");

        rp4.setPreferredSize(new java.awt.Dimension(643, 592));

        panelChartD.setMaximumSize(new java.awt.Dimension(643, 600));
        panelChartD.setPreferredSize(new java.awt.Dimension(0, 254));

        javax.swing.GroupLayout panelChartDLayout = new javax.swing.GroupLayout(panelChartD);
        panelChartD.setLayout(panelChartDLayout);
        panelChartDLayout.setHorizontalGroup(
            panelChartDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelChartDLayout.setVerticalGroup(
            panelChartDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(255, 153, 0));
        jPanel10.setPreferredSize(new java.awt.Dimension(643, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Settimana dal ");

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox2.setPreferredSize(new java.awt.Dimension(72, 24));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelChartWLayout = new javax.swing.GroupLayout(panelChartW);
        panelChartW.setLayout(panelChartWLayout);
        panelChartWLayout.setHorizontalGroup(
            panelChartWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelChartWLayout.setVerticalGroup(
            panelChartWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelChartW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelChartW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(255, 153, 0));
        jPanel12.setPreferredSize(new java.awt.Dimension(471, 30));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Utimi 7 giorni");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rp4Layout = new javax.swing.GroupLayout(rp4);
        rp4.setLayout(rp4Layout);
        rp4Layout.setHorizontalGroup(
            rp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
            .addComponent(panelChartD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
        );
        rp4Layout.setVerticalGroup(
            rp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rp4Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelChartD, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rightPanel.add(rp4, "card6");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sideLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sideLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseEntered

        if(active != 1)
        {
            panel1.setBackground(sColor);
        }
    }//GEN-LAST:event_panel1MouseEntered

    private void panel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseExited
        if(active != 1){
            panel1.setBackground(dColor);
        }
    }//GEN-LAST:event_panel1MouseExited

    private void panel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseEntered
        if(active != 2)
        {
            panel2.setBackground(sColor);
        }
    }//GEN-LAST:event_panel2MouseEntered

    private void panel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseExited
        if(active != 2)
        {
            panel2.setBackground(dColor);
        }
    }//GEN-LAST:event_panel2MouseExited

    private void panel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel3MouseEntered
        if(active != 3)
        {
            panel3.setBackground(sColor);
        }
    }//GEN-LAST:event_panel3MouseEntered

    private void panel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel3MouseExited
        if(active != 3)
        {
            panel3.setBackground(dColor);
        }
    }//GEN-LAST:event_panel3MouseExited

    private void panel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel4MouseEntered
        if(active != 4)
        {
            panel4.setBackground(sColor);
        }
    }//GEN-LAST:event_panel4MouseEntered

    private void panel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel4MouseExited
        if(active != 4)
        {
            panel4.setBackground(dColor);
        }
    }//GEN-LAST:event_panel4MouseExited

    private void panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseClicked

    }//GEN-LAST:event_panel1MouseClicked

    private void panel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseClicked

    }//GEN-LAST:event_panel2MouseClicked

    private void panel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel3MouseClicked
        
    }//GEN-LAST:event_panel3MouseClicked

    private void panel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel4MouseClicked
        
    }//GEN-LAST:event_panel4MouseClicked

    private void panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MousePressed
        active = 1;
        panel2.setBackground(dColor);
        panel3.setBackground(dColor);
        panel4.setBackground(dColor);
        rp1.setVisible(true);
        rp2.setVisible(false);
        rp3.setVisible(false);
        rp4.setVisible(false);
        panelChartD.setVisible(false);
        panelChartW.setVisible(false);
        
        rP1_inv2.setText(""+Util.getTotGiorno((DefaultTableModel) tab_ven.getModel(),LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))));
    }//GEN-LAST:event_panel1MousePressed

    private void panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MousePressed
        active = 2;
        panel1.setBackground(dColor);
        panel3.setBackground(dColor);
        panel4.setBackground(dColor);
        rp1.setVisible(false);
        rp2.setVisible(true);
        rp3.setVisible(false);
        rp4.setVisible(false);
        panelChartD.setVisible(false);
        panelChartW.setVisible(false);
    }//GEN-LAST:event_panel2MousePressed

    private void panel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel3MousePressed
        active = 3;
        panel1.setBackground(dColor);
        panel2.setBackground(dColor);
        panel4.setBackground(dColor); 
        rp1.setVisible(false);
        rp2.setVisible(false);
        rp3.setVisible(true);
        rp4.setVisible(false);
        panelChartD.setVisible(false);
        panelChartW.setVisible(false);
    }//GEN-LAST:event_panel3MousePressed

    private void panel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel4MousePressed
        active = 4;
        panel1.setBackground(dColor);
        panel2.setBackground(dColor);
        panel3.setBackground(dColor);
        rp1.setVisible(false);
        rp2.setVisible(false);
        rp3.setVisible(false);
        rp4.setVisible(true);
        
        DefaultTableModel vendite = (DefaultTableModel) tab_ven.getModel();
        
        
        
        vendite.addTableModelListener((TableModelEvent e) -> {
            Util.updatePanelChartDaily(dailyChart, vendite,jComboBox1.getSelectedItem().toString());
            Util.updatePanelChartWeekly(weeklyChart, vendite, jComboBox2.getSelectedItem().toString().substring(0, 10));
        });
        
        jComboBox1.addActionListener(e -> {
            Util.updatePanelChartDaily(dailyChart, vendite, jComboBox1.getSelectedItem().toString());
        });
        
        jComboBox2.addActionListener(e -> {
            Util.updatePanelChartWeekly(weeklyChart, vendite, jComboBox2.getSelectedItem().toString().substring(0, 10));
        });
        
        
        
        panelChartD.setVisible(true);
        panelChartD.revalidate();
        panelChartD.repaint();
        panelChartW.setVisible(true);
        panelChartW.revalidate();
        panelChartW.repaint();
        
    }//GEN-LAST:event_panel4MousePressed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int selectedRow = tab_inv.getSelectedRow(); //se diversa da -1 allora la riga e' stata selezionata
        if(selectedRow!=-1){
            String codice = tab_inv.getValueAt(selectedRow,0).toString();
            String denominazione = tab_inv.getValueAt(selectedRow,1).toString();
            String prezzo = tab_inv.getValueAt(selectedRow,2).toString();
            String quantita = tab_inv.getValueAt(selectedRow,3).toString();

            
            editInventory mod = new editInventory(null, true,codice,denominazione,prezzo,quantita,tab_inv,selectedRow,rP1_inv);
            mod.setLocationRelativeTo(this);
            mod.setVisible(true);
        }
        else{
            errorMsg err = new errorMsg(null,true);
            err.setLocationRelativeTo(this);
            err.setMessage("Seleziona un dato nella tabella e poi premi sul pulasante se vuoi modificarlo!");
            err.setVisible(true);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMousePressed
        DefaultTableModel model = (DefaultTableModel) tab_inv.getModel();
        addInventory agg = new addInventory(null, true,model,rP1_inv);
        agg.setLocationRelativeTo(this);
        agg.setVisible(true);
    }//GEN-LAST:event_btn_addMousePressed

    private void btn_delMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_delMousePressed
        int selectedRow = tab_inv.getSelectedRow();
        
        if(selectedRow!=-1){
            if(tab_inv.getRowSorter()!=null){
                DefaultTableModel model = (DefaultTableModel) tab_inv.getModel();
                selectedRow = tab_inv.getRowSorter().convertRowIndexToModel(selectedRow);
                model.removeRow(selectedRow);
                rP1_inv.setText(String.valueOf(countItemsInventory(model)));
            } else{
                DefaultTableModel model = (DefaultTableModel) tab_inv.getModel();
                model.removeRow(selectedRow);
                rP1_inv.setText(String.valueOf(countItemsInventory(model)));
                try {
                    fileUtils.salvaInventario((DefaultTableModel) tab_inv.getModel(), "./inventario.txt");
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else{
            errorMsg err = new errorMsg(null,true);
            err.setLocationRelativeTo(this);
            err.setMessage("Seleziona un dato nella tabella e poi premi sul pulasante RIMUOVI se vuoi eliminarlo!");
            err.setVisible(true);
        }
    }//GEN-LAST:event_btn_delMousePressed

    private void searchBarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarInventarioActionPerformed

    private void searchBarInventarioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_searchBarInventarioInputMethodTextChanged
        
    }//GEN-LAST:event_searchBarInventarioInputMethodTextChanged

    private void searchBarInventarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarInventarioKeyPressed
        
    }//GEN-LAST:event_searchBarInventarioKeyPressed

    private void searchBarInventarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarInventarioKeyTyped
        //Ricerca valori
        String text = searchBarInventario.getText();
            if(text.length() == 0) {
               sorter.setRowFilter(null);
            } else {
               try {
                  sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text)); //(?i) permette di cercare tutte le parole tralasciando il maiuscolo o minuscolo
               } catch(PatternSyntaxException pse) {
                     System.out.println("Bad regex pattern");
               }
             }
    }//GEN-LAST:event_searchBarInventarioKeyTyped

    private void searchBarInventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarInventarioMousePressed
        if(searchBarInventario.getText().equals("Ricerca prodotti...")){
            searchBarInventario.setText("");
        }
    }//GEN-LAST:event_searchBarInventarioMousePressed

    private void btn_add1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add1MousePressed

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
        DefaultTableModel inv = (DefaultTableModel) tab_inv.getModel();
        DefaultTableModel ven = (DefaultTableModel) tab_ven.getModel();
        sellingMode sm = new sellingMode(this, true,inv,ven,rP1_inv);
        sm.setLocationRelativeTo(jScrollPane4);
        sm.setVisible(true);
    }//GEN-LAST:event_btn_add1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void btn_showMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_showMousePressed

    private void btn_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showActionPerformed
        int selectedRow = tab_ven.convertRowIndexToModel(tab_ven.getSelectedRow());
        
        if(selectedRow!=-1){
            DefaultTableModel model = (DefaultTableModel) tab_ven.getModel();
            Receipt r = new Receipt(this, true, (ArrayList<Prodotto>) model.getValueAt(selectedRow, 2));
            r.setLocationRelativeTo(jScrollPane4);
            r.setVisible(true);
        }
        else{
            errorMsg err = new errorMsg(this, true);
            err.setLocationRelativeTo(jScrollPane4);
            err.setMessage("Seleziona una riga prima di cliccare il pulsante mostra!");
            err.setVisible(true);
        }
    }//GEN-LAST:event_btn_showActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void resetOnClick(){
        panel1.setBackground(dColor);
    }
    
    private void tableSearch(){
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tab_inv.getModel());
        tab_inv.setRowSorter(sorter);
        
    }
    
    public static int countItemsInventory(TableModel model){
        int rowCount = model.getRowCount();
        int qtyTot = 0;
        
        for(int i=0;i<rowCount;i++){
            qtyTot += Integer.parseInt(model.getValueAt(i, 3).toString());
        }
        return qtyTot;
    }
    
    private void insertDataComboBoxs(){
        ArrayList<String> dates = Util.getLast7Days();
        
        for (String date : dates) {
            jComboBox1.addItem(date);
        }
        
        dates = Util.getWeeksFromStartDateToToday();
        
        for(String date : dates) {
            jComboBox2.addItem(date);
        }
        
    }
    
    private void sortByColumn(JTable t){
        TableRowSorter<TableModel> sort = new TableRowSorter<>(t.getModel());
        t.setRowSorter(sort);

            // Replace columnIndex with the index of the column you want to sort by (0-based)
        sort.setSortKeys(Collections.singletonList(new RowSorter.SortKey(3, SortOrder.DESCENDING)));
        sort.sort();
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_add1;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_show;
    private javax.swing.JPanel counterInvPanel;
    private javax.swing.JPanel counterVenPanel;
    private javax.swing.JPanel counterVenPanel1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel p1_text;
    private javax.swing.JLabel p2_text;
    private javax.swing.JLabel p3_text;
    private javax.swing.JLabel p4_text;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panelChartD;
    private javax.swing.JPanel panelChartW;
    private javax.swing.JLabel rP1_inv;
    private javax.swing.JLabel rP1_inv1;
    private javax.swing.JLabel rP1_inv2;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel rp1;
    private javax.swing.JPanel rp2;
    private javax.swing.JPanel rp3;
    private javax.swing.JPanel rp4;
    private javax.swing.JTextField searchBarInventario;
    private javax.swing.JPanel sideLeftPanel;
    private javax.swing.JLabel sideLeftPanel_text;
    private javax.swing.JTable tab_inv;
    private javax.swing.JTable tab_ven;
    // End of variables declaration//GEN-END:variables
}


