/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sal.gui;

import java.io.IOException;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import sal.gui.core.Prodotto;
import sal.gui.core.fileUtils;

/**
 *
 * @author Salvatore Minasola
 */
public class sellingMode extends javax.swing.JDialog {
    private DefaultTableModel inv;
    private DefaultTableModel ven;
    private JLabel label;
    private ArrayList<Prodotto> prodottiVenduti;
    
    /**
     * Creates new form sellingMode
     */
    public sellingMode(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextField1.requestFocus();
    }
    
    public sellingMode(java.awt.Frame parent, boolean modal,DefaultTableModel inv,DefaultTableModel ven,JLabel label) {
        super(parent, modal);
        this.inv = inv;
        this.ven = ven;
        this.label = label;
        initComponents();
        jTextField1.requestFocus();
        prodottiVenduti = new ArrayList<>();
    }
    
    private void updateTotaleVendita(DefaultTableModel vendite){
        float totale = 0;
        if(vendite.getRowCount()>0){
            for(int i=0; i<vendite.getRowCount();i++)
            {
                totale += Float.parseFloat(vendite.getValueAt(i, 4).toString());
            }
            lbl_tot.setText(Float.toString(totale));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_addToSell = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_tot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("SCANNERIZZA CODICE:");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prodotto", "Codice", "Prezzo", "Quantita", "Tot"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_addToSell.setBackground(new java.awt.Color(0, 153, 51));
        btn_addToSell.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_addToSell.setText("COMPLETA VENDITA");
        btn_addToSell.setMaximumSize(new java.awt.Dimension(85, 23));
        btn_addToSell.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_addToSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addToSellMousePressed(evt);
            }
        });
        btn_addToSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addToSellActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel2.setText("TOTALE:");

        lbl_tot.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_tot.setText("0.0");
        lbl_tot.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn_addToSell, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_addToSell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(lbl_tot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        //Per evitare errori durante lettura codici
        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(sellingMode.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        String codice = jTextField1.getText().toLowerCase();
        DefaultTableModel vendite = (DefaultTableModel)jTable1.getModel();
        jTextField1.setText("");
        boolean found = false;
        
        
        for(int i=0; i<inv.getRowCount(); i++){
            if(codice.toLowerCase().equals(inv.getValueAt(i, 1).toString().toLowerCase())){
                if(vendite.getRowCount() > 0){
                    for(int j=0; j<vendite.getRowCount();j++){
                        if(vendite.getValueAt(j, 1).toString().equals(codice)){
                            int qty = Integer.parseInt(vendite.getValueAt(j, 3).toString()) + 1;
                            float prezzo = Float.parseFloat(vendite.getValueAt(j, 2).toString());
                            vendite.setValueAt(qty, j, 3);
                            vendite.setValueAt(qty*prezzo  , j, 4);
                            updateTotaleVendita(vendite);
                            return;
                        }
                    }
                }
                
                Object nome = inv.getValueAt(i, 0);
                Object prezzo = inv.getValueAt(i, 2);
                vendite.addRow(new Object[]{nome,codice,prezzo,1,prezzo});
                updateTotaleVendita(vendite);
                return;
            }
        }
        
        if(found==false){
            
            errorMsg err = new errorMsg(null,true);
            err.setLocationRelativeTo(this);
            err.setMessage("Prodotto non trovato in inventario");
            err.setVisible(true);
            
            
            addInventory agg = new addInventory(null, true,inv,label);
            agg.setLocationRelativeTo(this);
            agg.setVisible(true);
        }
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btn_addToSellMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addToSellMousePressed
      

    }//GEN-LAST:event_btn_addToSellMousePressed

    private void btn_addToSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addToSellActionPerformed
        DefaultTableModel vendite = (DefaultTableModel) jTable1.getModel();
        float tot = 0;
        
        if(vendite.getRowCount()<=0){
            errorMsg err = new errorMsg(null, true);
            err.setLocationRelativeTo(this);
            err.setMessage("Non puo essere effettuata l'operazione se la tabella vendita e' vuota");
            err.setVisible(true);
        }
        else{
            ArrayList<Prodotto> prodottiVen = new ArrayList<>();
            for(int i=0;i<vendite.getRowCount();i++){
                String codice = vendite.getValueAt(i, 1).toString();
                String nomeProdotto = vendite.getValueAt(i, 0).toString();
                float prezzo = Float.parseFloat(vendite.getValueAt(i, 2).toString());
                int quantita = Integer.parseInt(vendite.getValueAt(i, 3).toString());
                tot += prezzo*quantita;
         
                
                prodottiVen.add(new Prodotto(codice,nomeProdotto,prezzo,quantita));
            }
            LocalDateTime data = LocalDateTime.now();
            data = data.truncatedTo(ChronoUnit.MINUTES);
            ven.addRow(new Object[]{ven.getRowCount()+1,tot,prodottiVen,data});
            try {
                fileUtils.salvaVendite(ven, "./vendite.txt");
            } catch (IOException ex) {
                Logger.getLogger(sellingMode.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_btn_addToSellActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sellingMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sellingMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sellingMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sellingMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sellingMode dialog = new sellingMode(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addToSell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_tot;
    // End of variables declaration//GEN-END:variables
}
